<?php

namespace {
  exit("This file should not be included, only analyzed by your IDE");
}

/**
 * @global array{
 *     'title': string,
 *     'write_prefix': string,
 *     'auth_table': string,
 *     'config_table': string,
 *     'group_table': string,
 *     'group_member_table': string,
 *     'board_table': string,
 *     'board_file_table': string,
 *     'board_good_table': string,
 *     'board_new_table': string,
 *     'login_table': string,
 *     'mail_table': string,
 *     'member_table': string,
 *     'memo_table': string,
 *     'poll_table': string,
 *     'poll_etc_table': string,
 *     'point_table': string,
 *     'popular_table': string,
 *     'scrap_table': string,
 *     'visit_table': string,
 *     'visit_sum_table': string,
 *     'uniqid_table': string,
 *     'autosave_table': string,
 *     'cert_history_table': string,
 *     'qa_config_table': string,
 *     'qa_content_table': string,
 *     'content_table': string,
 *     'faq_table': string,
 *     'faq_master_table': string,
 *     'new_win_table': string,
 *     'menu_table': string,
 *     'social_profile_table': string,
 *     'member_cert_history_table': string,
 *     'connect_db': mysqli,
 *     'lo_location'?: string,
 *     'lo_url'?: string,
 *     'na_noti'?: string,
 *     'na_tag_log'?: string,
 *     'na_tag'?: string,
 *     'na_singo'?: string,
 *     'na_xp'?: string,
 *     'na_menu'?: string,
 *     'na_file'?: string,
 *     'na_history'?: string,
 *     'board_rate_average_table'?: string,
 * } $g5
 */

/**
 * @global array{
 *     'cf_id': string,
 *     'cf_title': string,
 *     'cf_theme': string,
 *     'cf_admin': string,
 *     'cf_admin_email': string,
 *     'cf_admin_email_name': string,
 *     'cf_add_script': string,
 *     'cf_use_point': string,
 *     'cf_point_term': string,
 *     'cf_use_copy_log': string,
 *     'cf_use_email_certify': string,
 *     'cf_login_point': string,
 *     'cf_cut_name': string,
 *     'cf_nick_modify': string,
 *     'cf_new_skin': string,
 *     'cf_new_rows': string,
 *     'cf_search_skin': string,
 *     'cf_connect_skin': string,
 *     'cf_faq_skin': string,
 *     'cf_read_point': string,
 *     'cf_write_point': string,
 *     'cf_comment_point': string,
 *     'cf_download_point': string,
 *     'cf_write_pages': string,
 *     'cf_mobile_pages': string,
 *     'cf_link_target': string,
 *     'cf_bbs_rewrite': string,
 *     'cf_delay_sec': string,
 *     'cf_filter': string,
 *     'cf_possible_ip': string,
 *     'cf_intercept_ip': string,
 *     'cf_analytics': string,
 *     'cf_add_meta': string,
 *     'cf_syndi_token': string,
 *     'cf_syndi_except': string,
 *     'cf_member_skin': string,
 *     'cf_use_homepage': string,
 *     'cf_req_homepage': string,
 *     'cf_use_tel': string,
 *     'cf_req_tel': string,
 *     'cf_use_hp': string,
 *     'cf_req_hp': string,
 *     'cf_use_addr': string,
 *     'cf_req_addr': string,
 *     'cf_use_signature': string,
 *     'cf_req_signature': string,
 *     'cf_use_profile': string,
 *     'cf_req_profile': string,
 *     'cf_register_level': string,
 *     'cf_register_point': string,
 *     'cf_icon_level': string,
 *     'cf_use_recommend': string,
 *     'cf_recommend_point': string,
 *     'cf_leave_day': string,
 *     'cf_search_part': string,
 *     'cf_email_use': string,
 *     'cf_email_wr_super_admin': string,
 *     'cf_email_wr_group_admin': string,
 *     'cf_email_wr_board_admin': string,
 *     'cf_email_wr_write': string,
 *     'cf_email_wr_comment_all': string,
 *     'cf_email_mb_super_admin': string,
 *     'cf_email_mb_member': string,
 *     'cf_email_po_super_admin': string,
 *     'cf_prohibit_id': string,
 *     'cf_prohibit_email': string,
 *     'cf_new_del': string,
 *     'cf_memo_del': string,
 *     'cf_visit_del': string,
 *     'cf_popular_del': string,
 *     'cf_optimize_date': string,
 *     'cf_use_member_icon': string,
 *     'cf_member_icon_size': string,
 *     'cf_member_icon_width': string,
 *     'cf_member_icon_height': string,
 *     'cf_member_img_size': string,
 *     'cf_member_img_width': string,
 *     'cf_member_img_height': string,
 *     'cf_login_minutes': string,
 *     'cf_image_extension': string,
 *     'cf_flash_extension': string,
 *     'cf_movie_extension': string,
 *     'cf_formmail_is_member': string,
 *     'cf_page_rows': string,
 *     'cf_mobile_page_rows': string,
 *     'cf_visit': string,
 *     'cf_max_po_id': string,
 *     'cf_stipulation': string,
 *     'cf_privacy': string,
 *     'cf_open_modify': string,
 *     'cf_memo_send_point': string,
 *     'cf_mobile_new_skin': string,
 *     'cf_mobile_search_skin': string,
 *     'cf_mobile_connect_skin': string,
 *     'cf_mobile_faq_skin': string,
 *     'cf_mobile_member_skin': string,
 *     'cf_captcha_mp3': string,
 *     'cf_editor': string,
 *     'cf_cert_use': string,
 *     'cf_cert_find': string,
 *     'cf_cert_ipin': string,
 *     'cf_cert_hp': string,
 *     'cf_cert_simple': string,
 *     'cf_cert_kg_cd': string,
 *     'cf_cert_kg_mid': string,
 *     'cf_cert_use_seed': string,
 *     'cf_cert_kcb_cd': string,
 *     'cf_cert_kcp_cd': string,
 *     'cf_lg_mid': string,
 *     'cf_lg_mert_key': string,
 *     'cf_cert_limit': string,
 *     'cf_cert_req': string,
 *     'cf_sms_use': string,
 *     'cf_sms_type': string,
 *     'cf_icode_id': string,
 *     'cf_icode_pw': string,
 *     'cf_icode_server_ip': string,
 *     'cf_icode_server_port': string,
 *     'cf_icode_token_key': string,
 *     'cf_googl_shorturl_apikey': string,
 *     'cf_social_login_use': string,
 *     'cf_social_servicelist': string,
 *     'cf_payco_clientid': string,
 *     'cf_payco_secret': string,
 *     'cf_facebook_appid': string,
 *     'cf_facebook_secret': string,
 *     'cf_twitter_key': string,
 *     'cf_twitter_secret': string,
 *     'cf_google_clientid': string,
 *     'cf_google_secret': string,
 *     'cf_naver_clientid': string,
 *     'cf_naver_secret': string,
 *     'cf_kakao_rest_key': string,
 *     'cf_kakao_client_secret': string,
 *     'cf_kakao_js_apikey': string,
 *     'cf_captcha': string,
 *     'cf_recaptcha_site_key': string,
 *     'cf_recaptcha_secret_key': string,
 *     'cf_1_subj': string,
 *     'cf_2_subj': string,
 *     'cf_3_subj': string,
 *     'cf_4_subj': string,
 *     'cf_5_subj': string,
 *     'cf_6_subj': string,
 *     'cf_7_subj': string,
 *     'cf_8_subj': string,
 *     'cf_9_subj': string,
 *     'cf_10_subj': string,
 *     'cf_1': string,
 *     'cf_2': string,
 *     'cf_3': string,
 *     'cf_4': string,
 *     'cf_5': string,
 *     'cf_6': string,
 *     'cf_7': string,
 *     'cf_8': string,
 *     'cf_9': string,
 *     'cf_10': string,
 *     'na_optimize_date'?: string,
 * } $config
 */

/**
 * @global \Damoang\Lib\G5\Member\Member|array{
 *     'mb_no'?: string,
 *     'mb_id'?: string,
 *     'mb_password'?: string,
 *     'mb_name'?: string,
 *     'mb_nick'?: string,
 *     'mb_nick_date'?: string,
 *     'mb_email'?: string,
 *     'mb_homepage'?: string,
 *     'mb_level'?: string,
 *     'mb_sex'?: string,
 *     'mb_birth'?: string,
 *     'mb_tel'?: string,
 *     'mb_hp'?: string,
 *     'mb_certify'?: string,
 *     'mb_adult'?: string,
 *     'mb_dupinfo'?: string,
 *     'mb_zip1'?: string,
 *     'mb_zip2'?: string,
 *     'mb_addr1'?: string,
 *     'mb_addr2'?: string,
 *     'mb_addr3'?: string,
 *     'mb_addr_jibeon'?: string,
 *     'mb_signature'?: string,
 *     'mb_recommend'?: string,
 *     'mb_point'?: string,
 *     'mb_today_login'?: string,
 *     'mb_login_ip'?: string,
 *     'mb_datetime'?: string,
 *     'mb_ip'?: string,
 *     'mb_leave_date'?: string,
 *     'mb_intercept_date'?: string,
 *     'mb_email_certify'?: string,
 *     'mb_email_certify2'?: string,
 *     'mb_memo'?: string,
 *     'mb_lost_certify'?: string,
 *     'mb_mailling'?: string,
 *     'mb_sms'?: string,
 *     'mb_open'?: string,
 *     'mb_open_date'?: string,
 *     'mb_profile'?: string,
 *     'mb_memo_call'?: string,
 *     'mb_memo_cnt'?: string,
 *     'mb_scrap_cnt'?: string,
 *     'mb_1'?: string,
 *     'mb_2'?: string,
 *     'mb_3'?: string,
 *     'mb_4'?: string,
 *     'mb_5'?: string,
 *     'mb_6'?: string,
 *     'mb_7'?: string,
 *     'mb_8'?: string,
 *     'mb_9'?: string,
 *     'mb_10'?: string,
 *     'as_noti'?: string,
 *     'as_msg'?: string,
 *     'as_exp'?: string,
 *     'as_level'?: string,
 *     'as_max'?: string,
 *     'as_chadan'?: string,
 * } $member
 */

/**
 * @global \Damoang\Lib\G5\Board\BoardConfig|array{
 *     'bo_table'?: string,
 *     'bo_skin'?: string,
 *     'bo_mobile_skin'?: string,
 *     'bo_upload_count'?: string|int,
 *     'bo_use_dhtml_editor'?: string,
 *     'bo_subject'?: string,
 *     'bo_image_width'?: string|int,
 *     'gr_id'?: string,
 *     'bo_mobile_subject'?: string,
 *     'bo_device'?: string,
 *     'bo_admin'?: string,
 *     'bo_list_level'?: string,
 *     'bo_read_level'?: string,
 *     'bo_write_level'?: string,
 *     'bo_reply_level'?: string,
 *     'bo_comment_level'?: string,
 *     'bo_upload_level'?: string,
 *     'bo_download_level'?: string,
 *     'bo_html_level'?: string,
 *     'bo_link_level'?: string,
 *     'bo_count_delete'?: string,
 *     'bo_count_modify'?: string,
 *     'bo_read_point'?: string,
 *     'bo_write_point'?: string,
 *     'bo_comment_point'?: string,
 *     'bo_download_point'?: string,
 *     'bo_use_category'?: string,
 *     'bo_category_list'?: string,
 *     'bo_use_sideview'?: string,
 *     'bo_use_file_content'?: string,
 *     'bo_use_secret'?: string,
 *     'bo_select_editor'?: string,
 *     'bo_use_rss_view'?: string,
 *     'bo_use_good'?: string,
 *     'bo_use_nogood'?: string,
 *     'bo_use_name'?: string,
 *     'bo_use_signature'?: string,
 *     'bo_use_ip_view'?: string,
 *     'bo_use_list_view'?: string,
 *     'bo_use_list_file'?: string,
 *     'bo_use_list_content'?: string,
 *     'bo_table_width'?: string,
 *     'bo_subject_len'?: string,
 *     'bo_mobile_subject_len'?: string,
 *     'bo_page_rows'?: string,
 *     'bo_mobile_page_rows'?: string,
 *     'bo_new'?: string,
 *     'bo_hot'?: string,
 *     'bo_include_head'?: string,
 *     'bo_include_tail'?: string,
 *     'bo_content_head'?: string,
 *     'bo_mobile_content_head'?: string,
 *     'bo_content_tail'?: string,
 *     'bo_mobile_content_tail'?: string,
 *     'bo_insert_content'?: string,
 *     'bo_gallery_cols'?: string,
 *     'bo_gallery_width'?: string,
 *     'bo_gallery_height'?: string,
 *     'bo_mobile_gallery_width'?: string,
 *     'bo_mobile_gallery_height'?: string,
 *     'bo_upload_size'?: string,
 *     'bo_reply_order'?: string,
 *     'bo_use_search'?: string,
 *     'bo_order'?: string,
 *     'bo_count_write'?: string,
 *     'bo_count_comment'?: string,
 *     'bo_write_min'?: string,
 *     'bo_write_max'?: string,
 *     'bo_comment_min'?: string,
 *     'bo_comment_max'?: string,
 *     'bo_notice'?: string,
 *     'bo_use_email'?: string,
 *     'bo_use_cert'?: string,
 *     'bo_use_sns'?: string,
 *     'bo_use_captcha'?: string,
 *     'bo_sort_field'?: string,
 *     'bo_1_subj'?: string,
 *     'bo_2_subj'?: string,
 *     'bo_3_subj'?: string,
 *     'bo_4_subj'?: string,
 *     'bo_5_subj'?: string,
 *     'bo_6_subj'?: string,
 *     'bo_7_subj'?: string,
 *     'bo_8_subj'?: string,
 *     'bo_9_subj'?: string,
 *     'bo_10_subj'?: string,
 *     'bo_1'?: string,
 *     'bo_2'?: string,
 *     'bo_3'?: string,
 *     'bo_4'?: string,
 *     'bo_5'?: string,
 *     'bo_6'?: string,
 *     'bo_7'?: string,
 *     'bo_8'?: string,
 *     'bo_9'?: string,
 *     'bo_10'?: string,
 * } $board
 */

/**
 * @global array{
 *     'gr_device'?: string,
 *     'gr_subject'?: string,
 *     'gr_id'?: string,
 *     'gr_admin'?: string,
 *     'gr_use_access'?: string,
 *     'gr_order'?: string,
 *     'gr_1_subj'?: string,
 *     'gr_2_subj'?: string,
 *     'gr_3_subj'?: string,
 *     'gr_4_subj'?: string,
 *     'gr_5_subj'?: string,
 *     'gr_6_subj'?: string,
 *     'gr_7_subj'?: string,
 *     'gr_8_subj'?: string,
 *     'gr_9_subj'?: string,
 *     'gr_10_subj'?: string,
 *     'gr_1'?: string,
 *     'gr_2'?: string,
 *     'gr_3'?: string,
 *     'gr_4'?: string,
 *     'gr_5'?: string,
 *     'gr_6'?: string,
 *     'gr_7'?: string,
 *     'gr_8'?: string,
 *     'gr_9'?: string,
 *     'gr_10'?: string,
 * } $group
 */

/**
 * @global array{
 *     'qa_id'?: string,
 *     'qa_title'?: string,
 *     'qa_category'?: string,
 *     'qa_skin'?: string,
 *     'qa_mobile_skin'?: string,
 *     'qa_use_email'?: string,
 *     'qa_req_email'?: string,
 *     'qa_use_hp'?: string,
 *     'qa_req_hp'?: string,
 *     'qa_use_sms'?: string,
 *     'qa_send_number'?: string,
 *     'qa_admin_hp'?: string,
 *     'qa_admin_email'?: string,
 *     'qa_use_editor'?: string,
 *     'qa_subject_len'?: string,
 *     'qa_mobile_subject_len'?: string,
 *     'qa_page_rows'?: string,
 *     'qa_mobile_page_rows'?: string,
 *     'qa_image_width'?: string,
 *     'qa_upload_size'?: string,
 *     'qa_insert_content'?: string,
 *     'qa_include_head'?: string,
 *     'qa_include_tail'?: string,
 *     'qa_content_head'?: string,
 *     'qa_content_tail'?: string,
 *     'qa_mobile_content_head'?: string,
 *     'qa_mobile_content_tail'?: string,
 *     'qa_1_subj'?: string,
 *     'qa_2_subj'?: string,
 *     'qa_3_subj'?: string,
 *     'qa_4_subj'?: string,
 *     'qa_5_subj'?: string,
 *     'qa_1'?: string,
 *     'qa_2'?: string,
 *     'qa_3'?: string,
 *     'qa_4'?: string,
 *     'qa_5'?: string,
 * } $qaconfig
 */

/**
 * @global array{
 *     'php'?: mixed[],
 *     'sql'?: mixed[],
 * } $g5_debug
 */

/**
 * @global ?array{
 *     'wr_id'?: string,
 *     'wr_num'?: string,
 *     'wr_reply'?: string,
 *     'wr_parent'?: string,
 *     'wr_is_comment'?: string,
 *     'wr_comment'?: string,
 *     'wr_comment_reply'?: string,
 *     'ca_name'?: string,
 *     'wr_option'?: string,
 *     'wr_subject'?: string,
 *     'wr_content'?: string,
 *     'wr_seo_title'?: string,
 *     'wr_link1'?: string,
 *     'wr_link2'?: string,
 *     'wr_link1_hit'?: string,
 *     'wr_link2_hit'?: string,
 *     'wr_hit'?: string,
 *     'wr_good'?: string,
 *     'wr_nogood'?: string,
 *     'mb_id'?: string,
 *     'wr_password'?: string,
 *     'wr_name'?: string,
 *     'wr_email'?: string,
 *     'wr_homepage'?: string,
 *     'wr_datetime'?: string,
 *     'wr_file'?: string,
 *     'wr_last'?: string,
 *     'wr_ip'?: string,
 *     'wr_facebook_user'?: string,
 *     'wr_twitter_user'?: string,
 *     'wr_1'?: string,
 *     'wr_2'?: string,
 *     'wr_3'?: string,
 *     'wr_4'?: string,
 *     'wr_5'?: string,
 *     'wr_6'?: string,
 *     'wr_7'?: string,
 *     'wr_8'?: string,
 *     'wr_9'?: string,
 *     'wr_10'?: string,
 * } $write
 */

/** @global ''|string $bo_table */
/** @global 0|int $wr_id */
/** @global ''|string $qstr */
/** @global ''|'super'|'group'|'board' $is_admin */
/** @global bool $is_member */
/** @global bool $is_guest */
/** @global bool $is_mobile */
/** @global bool $set_device */
/** @global string $board_skin_path */
/** @global string $board_skin_url */
/** @global string $member_skin_path */
/** @global string $member_skin_url */
/** @global string $new_skin_path */
/** @global string $new_skin_url */
/** @global string $search_skin_path */
/** @global string $search_skin_url */
/** @global string $connect_skin_path */
/** @global string $connect_skin_url */
/** @global string $faq_skin_path */
/** @global string $faq_skin_url */
/** @global ''|string $sca */
/** @global ''|string $sfl */
/** @global ''|string $stx */
/** @global ''|string $sst */
/** @global ''|string $sod */
/** @global ''|string $sop */
/** @global ''|string $spt */
/** @global ''|string|int $page */
/** @global ''|string $w */
/** @global ''|string $url */
/** @global string $urlencode */
/** @global ''|string $gr_id */


// 나리야 빌더 -----------------------------------------------------------------
/**
 * @global \Damoang\Lib\G5\Board\SkinConfig|\Damoang\Theme\Damoang\Skin\Board\Basic\SkinConfig|mixed[] $boset
 */
