services:
    mysql:
        platform: linux/amd64
        image: mysql:5.7
        container_name: da_mysql
        environment:
            MYSQL_DATABASE: damoang
            MYSQL_USER: user
            MYSQL_PASSWORD: 1234
            MYSQL_ROOT_PASSWORD: root123
        ports:
            - "3306:3306"
        volumes:
            - .docker/mysql_data:/var/lib/mysql
            - .docker/initdb:/docker-entrypoint-initdb.d

    php:
        platform: linux/amd64
        container_name: da_php
        build:
            context: .docker/build/php
            dockerfile: Dockerfile
        ports:
            - "9000:9000"
        volumes:
            - ./:/var/www/html

    nginx:
        platform: linux/amd64
        container_name: da_nginx
        environment:
            - NGINX_PORT=80
        build:
            context: .docker/build/nginx
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html
            - .docker/build/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        ports:
            - "80:80"

    phpmyadmin:
        platform: linux/amd64
        image: phpmyadmin/phpmyadmin
        container_name: da_phpmyadmin
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: root123
        ports:
            - "8080:80"
        depends_on:
            - mysql

volumes:
    mysql_data:
